// SQLite-backed intake store. File location: server/data/intakes.db (git-ignored).
// API is intentionally identical to the previous in-memory implementation so
// no callers need to change.

import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SCREENING_SECTIONS, SCREENING_QUESTION_INDEX, formatScaleAnswer } from './screening-questions.js';
import { computeSectionAverages, countAnswered } from './screening-stats.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const DB_PATH = process.env.DB_PATH || path.join(DATA_DIR, 'intakes.db');

if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');
db.pragma('synchronous = NORMAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS intakes (
    id          TEXT PRIMARY KEY,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    data        TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_intakes_created_at ON intakes(created_at DESC);
`);

const stmts = {
  insert: db.prepare(`INSERT INTO intakes (id, created_at, updated_at, data) VALUES (?, ?, ?, ?)`),
  selOne: db.prepare(`SELECT data FROM intakes WHERE id = ?`),
  selAll: db.prepare(`SELECT data FROM intakes ORDER BY datetime(created_at) DESC`),
  update: db.prepare(`UPDATE intakes SET data = ?, updated_at = ? WHERE id = ?`),
  count:  db.prepare(`SELECT COUNT(*) AS n FROM intakes`),
};

function makeId() {
  return 'ink_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6);
}

function blankIntake() {
  return {
    id: makeId(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'new',
    currentStep: null,     // intake flow step tracker
    clientName: '',
    contactPreference: '',
    needCategory: '',
    urgencyFlag: 'low',
    crisisFlag: false,
    transcript: [],        // [{ role: 'user'|'assistant', content: '...', step: '...' }]
    structuredAnswers: {},  // filled by intake flow
    summary: '',           // generated by model after intake completes
    staffNotes: '',        // editable by staff in dashboard

    qaPairs: [],
    analysis: null,
    helpScore: null,
    severityOverride: null,
    severityOverrideReason: '',

    // Screening questionnaire (1-5 Likert across 3 sections, 17 questions total)
    screeningAnswers: { mental_health: {}, physical_health: {}, quality_of_life: {} },
    screeningComments: { mental_health: '', physical_health: '', quality_of_life: '', general: '' },
    screeningUpdatedAt: null,

    isDemoData: false,
  };
}

// ── Pure helpers (unchanged from Phase 2) ─────────────────────────────────

export function buildQAPairs(intake) {
  const urgencyAnswer =
    (intake.transcript || []).find(
      (m) => m.role === 'user' && m.step === 'ask_urgency'
    )?.content || '';

  const chatPairs = [
    { question: 'What is your first name?', answer: intake.clientName || '' },
    { question: 'How would you like us to reach you?', answer: intake.contactPreference || '' },
    { question: 'What kind of help do you need?', answer: intake.needCategory || '' },
    { question: 'Is this urgent or are you planning ahead?', answer: urgencyAnswer },
    { question: 'Tell me about your situation in your own words.', answer: intake.structuredAnswers?.situationSummary || '' },
  ];

  return [...chatPairs, ...buildScreeningPairs(intake.screeningAnswers, intake.screeningComments)];
}

function buildScreeningPairs(answers, comments = {}) {
  if (!answers) return [];

  const pairs = [];
  for (const section of SCREENING_SECTIONS) {
    for (const q of section.questions) {
      const value = answers[section.id]?.[q.id];
      if (!Number.isInteger(value) || value < 1 || value > 5) continue;

      const meta = SCREENING_QUESTION_INDEX[q.id];
      pairs.push({
        question: `${section.label} screening — ${meta.text} (1 = ${meta.lowLabel}, 5 = ${meta.highLabel})`,
        answer: formatScaleAnswer(value, meta.lowLabel, meta.highLabel),
      });
    }
  }

  const averages = computeSectionAverages(answers);
  const counts = countAnswered(answers).by_section;
  for (const section of SCREENING_SECTIONS) {
    const avg = averages[section.id];
    if (avg == null) continue;
    pairs.push({
      question: `${section.label} screening — section average`,
      answer: `${avg.toFixed(1)} of 5 across ${counts[section.id]} answered question${counts[section.id] === 1 ? '' : 's'}`,
    });
  }

  // Section comments
  for (const section of SCREENING_SECTIONS) {
    const comment = comments[section.id];
    if (comment && typeof comment === 'string' && comment.trim()) {
      pairs.push({
        question: `${section.label} screening — additional comments`,
        answer: comment.trim(),
      });
    }
  }
  if (comments.general && typeof comments.general === 'string' && comments.general.trim()) {
    pairs.push({
      question: 'General comments',
      answer: comments.general.trim(),
    });
  }

  return pairs;
}

const SECTION_POLARITY = {
  mental_health:   'higher = worse',
  physical_health: 'mixed; read each scale',
  quality_of_life: 'higher = better',
};

export function buildClientBlock(intake) {
  const lines = [];
  const sa = intake.structuredAnswers || {};

  const name = [sa.firstName, sa.lastName].filter(Boolean).join(' ').trim()
            || intake.clientName
            || '(not provided)';
  lines.push(`Name: ${name}`);

  const contactBits = [];
  if (sa.phone) contactBits.push(`phone ${sa.phone}`);
  if (sa.email) contactBits.push(`email ${sa.email}`);
  if (contactBits.length === 0 && intake.contactPreference) {
    contactBits.push(intake.contactPreference);
  }
  lines.push(`Contact: ${contactBits.length ? contactBits.join(', ') : '(not provided)'}`);

  const location = [sa.address, sa.city, sa.zip].filter(Boolean).join(', ');
  lines.push(`Location: ${location || '(not provided)'}`);

  if (intake.needCategory) {
    lines.push(`Stated category: ${intake.needCategory}`);
  }

  if (sa.situationSummary && String(sa.situationSummary).trim()) {
    lines.push(`Stated situation: "${String(sa.situationSummary).trim()}"`);
  }

  return lines.join('\n');
}

export function buildScreeningBlock(intake) {
  const answers = intake.screeningAnswers || {};
  const comments = intake.screeningComments || {};
  const blocks = [];

  for (const section of SCREENING_SECTIONS) {
    const secAnswers = answers[section.id] || {};
    const filledQs = section.questions.filter(
      (q) => Number.isInteger(secAnswers[q.id]) && secAnswers[q.id] >= 1 && secAnswers[q.id] <= 5
    );
    if (filledQs.length === 0) {
      blocks.push(`${section.label}: not answered.`);
      continue;
    }

    const avg = filledQs.reduce((s, q) => s + secAnswers[q.id], 0) / filledQs.length;
    blocks.push(
      `${section.label} (${filledQs.length}/${section.questions.length} answered, ` +
      `raw avg ${avg.toFixed(1)}/5; ${SECTION_POLARITY[section.id] || 'see labels'}):`
    );
    for (const q of section.questions) {
      const v = secAnswers[q.id];
      if (!Number.isInteger(v)) continue;
      blocks.push(`  ${q.id} [${q.lowLabel} → ${q.highLabel}]: ${v}`);
    }
  }

  const commentLines = [];
  for (const section of SCREENING_SECTIONS) {
    const c = (comments[section.id] || '').trim();
    if (c) commentLines.push(`${section.label}: "${c}"`);
  }
  const generalComment = (comments.general || '').trim();
  if (generalComment) commentLines.push(`General: "${generalComment}"`);

  if (commentLines.length) {
    blocks.push('Comments:');
    for (const line of commentLines) blocks.push(`  ${line}`);
  }

  return blocks.join('\n');
}

// ── CRUD ───────────────────────────────────────────────────────────────────

export function create(overrides = {}) {
  const intake = { ...blankIntake(), ...overrides };
  intake.id = intake.id || makeId();
  stmts.insert.run(intake.id, intake.createdAt, intake.updatedAt, JSON.stringify(intake));
  return intake;
}

export function getAll() {
  return stmts.selAll.all().map((row) => JSON.parse(row.data));
}

export function getById(id) {
  const row = stmts.selOne.get(id);
  return row ? JSON.parse(row.data) : null;
}

export function update(id, patch) {
  const existing = getById(id);
  if (!existing) return null;
  const updatedAt = new Date().toISOString();
  const merged = { ...existing, ...patch, updatedAt };
  stmts.update.run(JSON.stringify(merged), updatedAt, id);
  return merged;
}

export function isEmpty() {
  return stmts.count.get().n === 0;
}
