// In-memory intake store. No persistence — restarts clear everything.

const intakes = new Map();

function makeId() {
  return 'ink_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6);
}

function blankIntake() {
  return {
    id: makeId(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'new',
    currentStep: null,     // intake flow step tracker
    clientName: '',
    contactPreference: '',
    needCategory: '',
    urgencyFlag: 'low',
    crisisFlag: false,
    transcript: [],        // [{ role: 'user'|'assistant', content: '...', step: '...' }]
    structuredAnswers: {},  // filled by intake flow
    summary: '',           // generated by model after intake completes
    staffNotes: '',        // editable by staff in dashboard
  };
}

export function create(overrides = {}) {
  const intake = { ...blankIntake(), ...overrides };
  intake.id = intake.id || makeId(); // keep generated id unless explicitly passed
  intakes.set(intake.id, intake);
  return intake;
}

export function getAll() {
  return Array.from(intakes.values()).sort(
    (a, b) => new Date(b.createdAt) - new Date(a.createdAt)
  );
}

export function getById(id) {
  return intakes.get(id) || null;
}

export function update(id, patch) {
  const existing = intakes.get(id);
  if (!existing) return null;
  Object.assign(existing, patch, { updatedAt: new Date().toISOString() });
  intakes.set(id, existing);
  return existing;
}
