// In-memory intake store. No persistence — restarts clear everything.

import { SCREENING_SECTIONS, SCREENING_QUESTION_INDEX, formatScaleAnswer } from './screening-questions.js';
import { computeSectionAverages, countAnswered } from './screening-stats.js';

const intakes = new Map();

function makeId() {
  return 'ink_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6);
}

function blankIntake() {
  return {
    id: makeId(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'new',
    currentStep: null,     // intake flow step tracker
    clientName: '',
    contactPreference: '',
    needCategory: '',
    urgencyFlag: 'low',
    crisisFlag: false,
    transcript: [],        // [{ role: 'user'|'assistant', content: '...', step: '...' }]
    structuredAnswers: {},  // filled by intake flow
    summary: '',           // generated by model after intake completes
    staffNotes: '',        // editable by staff in dashboard

    // NEW
    qaPairs: [],
    analysis: null,
    helpScore: null,
    severityOverride: null,
    severityOverrideReason: '',

    // Screening questionnaire (1-5 Likert across 3 sections, 17 questions total)
    screeningAnswers: { mental_health: {}, physical_health: {}, quality_of_life: {} },
    screeningComments: { mental_health: '', physical_health: '', quality_of_life: '', general: '' },
    screeningUpdatedAt: null,
  };
}

export function buildQAPairs(intake) {
  const urgencyAnswer =
    (intake.transcript || []).find(
      (m) => m.role === 'user' && m.step === 'ask_urgency'
    )?.content || '';

  const chatPairs = [
    { question: 'What is your first name?', answer: intake.clientName || '' },
    { question: 'How would you like us to reach you?', answer: intake.contactPreference || '' },
    { question: 'What kind of help do you need?', answer: intake.needCategory || '' },
    { question: 'Is this urgent or are you planning ahead?', answer: urgencyAnswer },
    { question: 'Tell me about your situation in your own words.', answer: intake.structuredAnswers?.situationSummary || '' },
  ];

  return [...chatPairs, ...buildScreeningPairs(intake.screeningAnswers, intake.screeningComments)];
}

function buildScreeningPairs(answers, comments = {}) {
  if (!answers) return [];

  const pairs = [];
  for (const section of SCREENING_SECTIONS) {
    for (const q of section.questions) {
      const value = answers[section.id]?.[q.id];
      if (!Number.isInteger(value) || value < 1 || value > 5) continue;

      const meta = SCREENING_QUESTION_INDEX[q.id];
      pairs.push({
        question: `${section.label} screening — ${meta.text} (1 = ${meta.lowLabel}, 5 = ${meta.highLabel})`,
        answer: formatScaleAnswer(value, meta.lowLabel, meta.highLabel),
      });
    }
  }

  const averages = computeSectionAverages(answers);
  const counts = countAnswered(answers).by_section;
  for (const section of SCREENING_SECTIONS) {
    const avg = averages[section.id];
    if (avg == null) continue;
    pairs.push({
      question: `${section.label} screening — section average`,
      answer: `${avg.toFixed(1)} of 5 across ${counts[section.id]} answered question${counts[section.id] === 1 ? '' : 's'}`,
    });
  }

  // Section comments
  for (const section of SCREENING_SECTIONS) {
    const comment = comments[section.id];
    if (comment && typeof comment === 'string' && comment.trim()) {
      pairs.push({
        question: `${section.label} screening — additional comments`,
        answer: comment.trim(),
      });
    }
  }
  if (comments.general && typeof comments.general === 'string' && comments.general.trim()) {
    pairs.push({
      question: 'General comments',
      answer: comments.general.trim(),
    });
  }

  return pairs;
}

export function create(overrides = {}) {
  const intake = { ...blankIntake(), ...overrides };
  intake.id = intake.id || makeId(); // keep generated id unless explicitly passed
  intakes.set(intake.id, intake);
  return intake;
}

export function getAll() {
  return Array.from(intakes.values()).sort(
    (a, b) => new Date(b.createdAt) - new Date(a.createdAt)
  );
}

export function getById(id) {
  return intakes.get(id) || null;
}

export function update(id, patch) {
  const existing = intakes.get(id);
  if (!existing) return null;
  Object.assign(existing, patch, { updatedAt: new Date().toISOString() });
  intakes.set(id, existing);
  return existing;
}
